version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  mysql:
    platform: linux/x86_64
    image: mysql:8
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: social_media_jpa
      MYSQL_ROOT_PASSWORD: 12345678
#      MYSQL_USER: root
#      MYSQL_PASSWORD: 12345678
#      MYSQL_ROOT_PASSWORD: 12345678



